export const agents = [
  {
    firstName: "Stephen",
    lastName: "Rutcowski",
    programs: ["Clozapine", "Nulojix", "Xiaflex", "Aveed"],
    load: 0,
    assignedJobs: [],
    available: true,
  },
  {
    firstName: "Andreal",
    lastName: "Willis",
    programs: ["Clozapine", "Xiaflex", "Alosetron", "Aveed"],
    load: 0,
    assignedJobs: [],
    available: true,
  },
  {
    firstName: "Bryce",
    lastName: "Fincher",
    programs: ["Clozapine", "Bosentan"],
    load: 0,
    assignedJobs: [],
    available: true,
  },
  {
    firstName: "Zach",
    lastName: "Barnes",
    programs: ["Clozapine", "Bosentan"],
    load: 0,
    assignedJobs: [],
    available: true,
  },
  {
    firstName: "Carvonne",
    lastName: "Stafford",
    programs: ["Clozapine", "Nulojix", "Aveed", "Xiaflex"],
    load: 0,
    assignedJobs: [],
    available: true,
  },
  {
    firstName: "Taylor",
    lastName: "Magin",
    programs: ["Clozapine", "Nulojix", "Aveed", "Xiaflex"],
    load: 0,
    assignedJobs: [],
    available: true,
  },
  {
    firstName: "Daisy",
    lastName: "Arenas",
    programs: ["Clozapine", "Alosetron", "Bosentan"],
    load: 0,
    assignedJobs: [],
    available: true,
  },
  {
    firstName: "Matt",
    lastName: "Kearns",
    programs: ["Clozapine", "Bosentan"],
    load: 0,
    assignedJobs: [],
    available: true,
  },
];

export const tasks = [
  {
    task: "CPMG PAEs",
    loadScore: 15,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Clozapine",
    priority: 1,
  },
  {
    task: "Bosentan PAEs",
    loadScore: 15,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Bosentan",
    priority: 2,
  },
  {
    task: "CPMG PAEs Backup",
    loadScore: 7,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Clozapine",
    priority: 3,
  },
  {
    task: "Notifications",
    loadScore: 5,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Clozapine",
    priority: 4,
  },
  {
    task: "Project 1",
    loadScore: 11,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Clozapine",
    priority: 5,
  },
  {
    task: "Project 2",
    loadScore: 7,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Clozapine",
    priority: 6,
  },
  {
    task: "Project 3",
    loadScore: 7,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Clozapine",
    priority: 7,
  },
  {
    task: "Project 4",
    loadScore: 7,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Clozapine",
    priority: 8,
  },
  {
    task: "Aveed",
    loadScore: 4,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Aveed",
    priority: 9,
  },
  {
    task: "Alosetron",
    loadScore: 4,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Alosetron",
    priority: 10,
  },
  {
    task: "Bosentan",
    loadScore: 4,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Bosentan",
    priority: 11,
  },
  {
    task: "Nulojix",
    loadScore: 4,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Nulojix",
    priority: 12,
  },
  {
    task: "Xiaflex",
    loadScore: 4,
    assigned: false,
    assignedAgent: "Unassigned",
    associatedProgram: "Xiaflex",
    priority: 13,
  },
];

export const editMode = false;

export const flipCardToggle = true;
